version: '3.8'

services:
  frontend:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "3002:80"
    env_file:
      - .env.production
    volumes:
      - .:/usr/src/app 
    restart:  unless-stopped